
url: "https://ghspace.fr"

menu:
  - name: "Maison" 
    url: /index.html
  - name: "Blog"
    url: /blog/index.html
  - name: "Adh√©sions"
    url: /dons.html
  - name: "Copaines"
    url: /copaines.html
  - name: "Contact"
    url: /contact.html
  - name: "RSS"
    class: right
    url: /rss.xml

style: /static/css/style.css
email: team@ghspace.fr
feed: rss.xml
